create table if not exists cloud_migration_inclusion(
cloud_migration_inclusion_list Integer not null,
cloud_migration_inclusion_list_description Integer null,
vendo_list varchar(255) null,
authorized_list varchar(255) null,
accompanied_rule_code varchar(255) null,
accompanied_rule_description varchar(255) null,
cloud_migration_available char null,
data_support varchar(255) null,
dev_integration varchar(255) null,
pipeline_tools varchar(255) null,
work_item_tools varchar(255) null,
custom_board varchar(255) null,
dashboard_name varchar(255) null,
approved_work_items varchar(255) null,
articatory_owner varchar(255) null,
dr_check varchar(255) null,
active_passive_mode Integer null,
module_to_validate varchar(255) null,
entity_state varchar(255) null,
remarks varchar(255) null,
constraint cloud_migration_inclusion_pk primary key(cloud_migration_inclusion_list));